# Netlify configuration file

[build]
  # The React app is in the 'client' folder, so Netlify will build it from there.
  base = "client"  # Specify that the frontend is located inside the 'client' folder
  publish = "client/dist"  # Vite's output folder (not 'client/build', it should be 'client/dist')
  
  # Serverless functions (Express app) are located inside the 'server/functions' folder
  functions = "server/functions"  # Directory containing serverless functions for backend

[[redirects]]
  # Redirect API requests to the serverless function handler (your Express routes)
  from = "/api/*"
  to = "/.netlify/functions/:splat"  # The Netlify function path
  status = 200
