export const surpriseMePrompts = [
  'an armchair in the shape of an avocado',
  'a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers',
  'teddy bears shopping for groceries in Japan, ukiyo-e',
  'an oil painting by Matisse of a humanoid robot playing chess',
  'panda mad scientist mixing sparkling chemicals, digital art',
  "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
  '3D render of a cute tropical fish in an aquarium on a dark blue background, digital art',
  'an astronaut lounging in a tropical resort in space, vaporwave',
  'an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background',
  'a stained glass window depicting a hamburger and french fries',
  'a pencil and watercolor drawing of a bright city in the future with flying cars',
  'a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art',
  'a fortune-telling shiba inu reading your fate in a giant hamburger, digital art',
  '"a sea otter with a pearl earring" by Johannes Vermeer',
  'an oil pastel drawing of an annoyed cat in a spaceship',
  'a painting of a fox in the style of Starry Night',
  'a bowl of soup that looks like a monster, knitted out of wool',
  'A plush toy robot sitting against a yellow wall',
  'A synthwave style sunset above the reflecting water of the sea, digital art',
  'Two futuristic towers with a skybridge covered in lush foliage, digital art',
  'A 3D render of a rainbow colored hot air balloon flying above a reflective lake',
  'A comic book cover of a superhero wearing headphones',
  'A centered explosion of colorful powder on a black background',
  'A photo of a Samoyed dog with its tongue out hugging a white Siamese cat',
  'A photo of a white fur monster standing in a purple room',
  "A photo of Michelangelo's sculpture of David wearing headphones djing",
  'A Samurai riding a Horse on Mars, lomography.',
  'A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography',
  'A realistic photograph of a young woman with blue eyes and blonde hair',
  'A man standing in front of a stargate to another dimension',
  'Spongebob Squarepants in the Blair Witch Project',
  'A velociraptor working at a hotdog stand, lomography',
  'A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens',
  'A BBQ that is alive, in the style of a Pixar animated movie',
  'A futuristic cyborg dance club, neon lights',
  'The long-lost Star Wars 1990 Japanese Anime',
  'A hamburger in the shape of a Rubik’s cube, professional food photography',
  'A Synthwave Hedgehog, Blade Runner Cyberpunk',
  'An astronaut encountering an alien life form on a distant planet, photography',
  'A Dinosaur exploring Cape Town, photography',
  'A Man falling in Love with his Computer, digital art',
  'A photograph of a cyborg exploring Tokyo at night, lomography',
  'Dracula walking down the street of New York City in the 1920s, black and white photography',
  'Synthwave aeroplane',
  'A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm',
  'A Space Shuttle flying above Cape Town, digital art',
  'A cat exploring a bustling city, wearing a detective hat, cartoon style',
  'A magical forest with rainbow-colored trees and talking animals, illustration',
  'A robot teaching kids how to play chess, digital art',
  'A superhero panda saving the day, comic book style',
  'A flying car zooming through the sky, futuristic city in the background',
  'A penguin learning to surf on a tropical beach, fun illustration',
  'A unicorn flying over a snowy mountain, fairy tale style',
  'A space explorer discovering an alien garden, digital painting',
  'A cat in a spacesuit exploring Mars, whimsical digital art',
  'A group of animals having a picnic in the park, cartoon art',
  'A magical book that tells stories when opened, digital painting',
  'A young inventor creating a flying bicycle, futuristic art',
  'A group of friends building a treehouse in a giant tree, digital illustration',
  'A tiny dragon playing with a ball of yarn, cute cartoon style',
  'A robot dog helping a child with homework, digital art',
  'A castle made entirely of candy, digital painting',
  'A giraffe wearing a bowtie, riding a bicycle, whimsical illustration',
  'A butterfly with wings made of colorful glass, 3D render',
  'A child and a lion on an adventure through the jungle, vibrant art',
  'A fairy godmother granting wishes with a sparkling wand, fantasy art',
  'A playful dolphin jumping over a rainbow, underwater scene',
  'A giant snowman helping children build a snow fort, winter scene',
  'A wizard teaching spells in an enchanted classroom, magical art',
  'A superhero dog saving the world from giant cupcakes, cartoon style',
  'A magic carpet ride over a vast desert, fairy tale art',
  'A bear with glasses reading a book in a cozy library, digital illustration',
  'A school bus flying through the clouds, whimsical concept art',
  'A robot working as a barista in a futuristic café, digital art',
  'A spaceship shaped like a whale, traveling through a cosmic ocean',
  'A frog wearing a suit, working in an office, funny digital art',
  'A dragon flying over a bustling medieval town, painting style',
  'A robot gardener planting flowers in a digital garden, futuristic art',
  'A young girl riding a magical lion, traveling through a forest',
  'A rocket ship made of candy, launching into space, bright art',
  'A puppy learning how to drive a car, humorous cartoon style',
  'A cat chef cooking in a high-tech kitchen, digital illustration',
  'A time machine built out of books, sending kids to the future, storybook art',
  'A snail with a rocket pack zooming across a field, fun illustration',
  'A pirate ship sailing across a giant coffee cup, whimsical design',
  'A superhero squirrel saving a forest from pollution, eco-friendly art',
  'A magical aquarium filled with floating jellyfish, 3D render',
  'A futuristic city on a cloud, flying cars zooming by',
  'A lion dressed as a knight, ready for an adventure, cartoon style',
  'A cat walking through a mystical portal into a magical land',
  'A wizard owl helping children with their homework, educational art',
  'A giant octopus playing chess with a robot, underwater scene',
  'A scientist raccoon inventing a new gadget in a workshop, cartoon style',
  'A group of kids discovering a hidden cave full of treasures, fantasy art',
  'A flying bicycle delivering letters in a futuristic city, digital art',
  'A panda in a spaceship traveling to the moon, adorable illustration',
  'A super-fast cheetah racing against a robot, futuristic concept art',
  'A magical forest with creatures that change colors, digital painting',
  'A snowman building a sandcastle on the beach, humorous art',
  'A forest made of giant mushrooms, inhabited by friendly creatures',
  'A castle in the sky made of clouds, floating above a city, digital art',
  'A robot playing the piano, in a cozy futuristic home',
  'A squirrel inventing new gadgets in a high-tech lab, cartoon style',
  'A fairy riding a butterfly through a flower garden, whimsical art',
  'A cat playing soccer with mice in a park, funny cartoon style',
  'A superhero raccoon saving a city from a giant watermelon, cartoon style',
  'A child flying a kite shaped like a dragon, bright and colorful art',
  'A robot taking care of a garden, futuristic farming scene',
  'A giant rabbit living in a tree house, whimsical illustration',
  'A robot walking a dog in the park, futuristic city backdrop',
  'A group of friends riding hoverboards down a futuristic street',
  'A magical unicorn pulling a cart of stars through the sky',
  'A penguin making ice cream in a cozy shop, digital illustration',
  'A jellyfish with a lightbulb inside it, glowing underwater, digital art',
  'A kid inventing a machine that turns wishes into toys, fun art',
  'A dragon teaching kids how to cook, fantasy-inspired scene',
  'A superhero team made up of animals, saving the world together',
  'A dragon breathing fire to light up a cold winter night, magical scene',
  'A futuristic robot holding a soccer ball, ready to play, digital art',
  'A giant sunflower with faces of animals in the petals, cartoon style',
  'A spaceship shaped like a cat, traveling across a nebula',
  'A dog in a space suit chasing an alien through a spaceship, cartoon style',
  'A race of flying cars in a neon-lit city, futuristic racing scene',
  'A magical library with books that float around, whimsical digital art',
  'A baby elephant learning how to swim in the ocean, cute art',
  'A talking lion giving advice to a young adventurer, storybook style',
  'A rocket ship made of LEGO blocks, launching into space',
  'A secret garden filled with glowing plants, mystical and serene',
  'A giant robot playing with children in a park, digital painting',
  'A group of penguins building a snow fort, fun winter art',
  'A chef monkey making delicious meals, cartoon art',
  'A spaceship shaped like a whale exploring the universe, fantasy art',
  'A robot helping a farmer harvest crops in a futuristic world',
  'A magical dragon protecting a hidden treasure in a cave',
  'A cat astronaut floating in space, looking out at Earth',
  'A magical castle floating in the sky, surrounded by flying creatures',
  'A boy riding a dragon through the clouds, fantasy art',
  'A friendly ghost teaching kids how to draw, spooky art',
  'A super-powered cat with a cape saving the world, comic book style',
  'A bear with a backpack going on a camping adventure, digital art',
  'A giant snail pulling a cart through a busy city street',
  'A group of animals starting a band, playing instruments together',
  'A magical underwater city made of glowing coral, 3D art',
  'A magical forest with glowing trees and sparkling flowers, fantasy scene',
  'A robot chef cooking in a futuristic kitchen, digital art',
  'A rabbit building a snow fort in the winter, adorable art',
  'A magical rainbow stretching across the sky, lighting up the landscape',
  'A group of animals working together to build a treehouse',
  'A super-fast cheetah racing a robot down a track',
  'A penguin playing a game of soccer, funny cartoon style',
  'A cat wearing a wizard hat, casting magical spells in the forest',
  'A futuristic city made of glass and metal, glowing at night',
  'A superhero dog flying through the sky, saving the city',
  'A lion wearing a crown, ruling over a magical kingdom',
  'A futuristic robot delivering packages in a neon-lit city',
  'A magical princess riding a horse through a sparkling forest',
  'A flying car zooming above a futuristic cityscape at night',
  'A friendly alien visiting Earth to make new friends, cartoon style',
  'A whale swimming through space, surrounded by stars and planets',
  'A penguin learning to fly using a jetpack, cartoon art',
  'A magical ice castle made of diamonds, glowing in the night',
  'A spaceship shaped like a dragon exploring the galaxy',
  'A raccoon detective solving mysteries in a bustling city',
  'A robot dog playing fetch with a child in the park',
  'A giant friendly octopus hugging a ship, underwater scene',
  'A superhero squirrel building a giant treehouse, fun art',
  'A magical forest with floating rocks and glowing mushrooms',
  'A dog riding a skateboard through a futuristic city',
  'A cat riding a flying broomstick through a mystical sky',
  'A giant panda creating art in a peaceful forest, digital painting',
  'A fairy sprinkling magic dust over a flower garden, whimsical art',
  'A futuristic city built entirely out of crystals, glowing under the stars',
  'A magical forest where trees have faces and talk to travelers',
  'A robotic fish exploring the deep sea, surrounded by glowing coral',
  'A child creating a giant ice sculpture of a dragon in the snow',
  'A raccoon dressed as a knight, guarding a secret treasure chest',
  'A fairy flying above a city at night, casting a glowing trail behind',
  'A dinosaur walking through a peaceful park, interacting with children',
  'A spaceship shaped like a giant jellybean, traveling through the stars',
  'A panda painting a masterpiece in a sunny art studio',
  'A group of robots having a picnic in a park, chatting about technology',
  'A super-fast rabbit racing through a futuristic tunnel, digital art',
  'A time traveler visiting a Victorian-era city with advanced gadgets',
  'A young girl creating her own robot from scrap materials, futuristic scene',
  'A friendly alien exploring Earth’s gardens, taking notes on plants',
  'A giant turtle carrying an entire island on its back, fantasy art',
  'A penguin detective solving mysteries in the Arctic, cartoon style',
  'A spaceship shaped like a flower, drifting through a nebula',
  'A cat flying a kite in a clear blue sky, enjoying a sunny day',
  'A giant dragon made of fire flying over a peaceful village',
  'A group of magical creatures living together in a floating island',
  'A robot learning to paint, creating a colorful masterpiece',
  'A child and a bear on a camping trip in the woods, digital art',
  'A young inventor creating a flying bicycle, futuristic concept',
  'A giant moon glowing over a peaceful ocean, magical scene',
  'A school of fish forming a giant heart shape underwater',
  'A group of friendly monsters teaching kids how to make art',
  'A futuristic city with buildings made of light, glowing at night',
  'A cat exploring an abandoned castle, discovering hidden treasures',
  'A wizard creating a portal to another dimension, surrounded by magic',
  'A superhero dolphin saving the ocean from pollution, digital art',
  'A group of children flying colorful kites on a warm spring day',
  'A friendly dragon sharing stories with kids in a magical forest',
  'A futuristic space station orbiting a distant planet, bustling with activity',
  'A cat in a hot air balloon, floating over a peaceful countryside',
  'A young girl with a glowing umbrella, walking through a magical rainstorm',
  'A giant fish swimming through the sky above a city at sunset',
  'A glowing rainbow made of stars arcing across the night sky',
  'A child and a puppy on a treasure hunt through a tropical jungle',
  'A cat exploring a cave filled with glowing crystals, magical atmosphere',
  'A group of animals planning a surprise birthday party for a friend',
  'A dragon and a phoenix flying through the clouds, surrounded by sparks',
  'A robot bird perched on a tree branch, observing the world below',
  'A magical treehouse in a giant oak tree, surrounded by floating lights',
  'A group of friends creating a giant sandcastle on a beach',
  'A mermaid singing a lullaby to the ocean, digital art',
  'A friendly giant walking through a city, helping people along the way',
  'A young wizard learning new spells in an enchanted library',
  'A futuristic farm where robots take care of the crops, digital art',
  'A castle made of candy and chocolate, surrounded by candy trees',
  'A magical butterfly flying through a glowing forest at night',
  'A group of animals hosting a talent show in a cozy theater',
  'A superhero dog flying through the clouds, ready for action',
  'A magical kingdom built on clouds, where everything is made of light',
  'A robot exploring an ancient ruin, discovering hidden artifacts',
  'A dragon flying above a city made entirely of mirrors',
  'A young child finding a magical book that can bring stories to life',
  'A group of children building a robot out of scrap materials, working together',
  'A space explorer discovering a new planet with friendly alien lifeforms',
  'A cat playing the violin in a cozy, dimly lit room, playing a beautiful melody',
  'A futuristic train traveling through a tunnel of light, zooming at high speed',
  'A talking tree giving advice to travelers in a mystical forest',
  'A superhero bear stopping a runaway train, saving the day',
  'A futuristic water park with flying slides and holographic dolphins',
  'A robot puppy learning to fetch, playing with a child in the yard',
  'A giant flower opening up to reveal a hidden treasure inside',
  'A child and a rabbit exploring an enchanted forest filled with glowing mushrooms',
  'A spaceship landing on a peaceful moon, surrounded by floating crystals',
  'A rainbow made of candy stretching across a bright blue sky',
  'A giant cloud shaped like an elephant, floating through a clear sky',
  'A group of kids solving a mystery in a spooky, abandoned mansion',
  'A forest of giant trees with glowing fireflies lighting the way',
  'A magical potion brewing in a cauldron, sending colorful smoke into the air',
  'A futuristic park with robots playing chess with kids, digital art',
  'A cat and a dog discovering a hidden tunnel under a tree, exploring together',
  'A giant octopus playing hide-and-seek with children, underwater scene',
  'A magical library where the books float around, glowing with light',
  'A young girl and her pet robot flying a kite together on a hilltop',
  'A dragon and a unicorn racing through the clouds, fast-paced scene',
  'A group of children discovering a magical pond where they can talk to animals',
  'A wizard casting spells to make the flowers bloom in a magical garden',
  'A futuristic city with holographic billboards and flying vehicles',
  'A family of animals on a road trip through a forest, having fun together',
  'A robot with a backpack going on an adventure in a bustling city',
  'A magical creature living in a hollow tree, watching over a secret garden',
  'A superhero owl flying through the night sky, ready to protect the city',
  'A friendly ghost giving kids a tour of an old haunted mansion',
  'A magical cloud castle floating above a busy city, glowing in the sun',
  'A group of animals preparing for a grand feast, setting up tables in the forest',
  'A young girl painting a mural on a giant wall, bringing it to life',
  'A rocket ship shaped like a giant ice cream cone, launching into space',
  'A dinosaur and a dragon becoming friends on an adventure, running through a magical land',
  'A cat exploring an ancient temple filled with golden treasures and traps',
  'A robot dog learning how to dance, impressing a group of children',
  'A young wizard learning to fly on a broomstick, zooming through the clouds',
  'A spaceship shaped like a giant flower, taking children on an intergalactic tour',
  'A mermaid swimming with dolphins in the deep blue ocean, magical scene',
  'A group of animals working together to build a treehouse, cartoon style',
  'A futuristic robot serving ice cream at a glowing stand in the park',
  'A magical forest where the trees whisper ancient secrets to those who listen',
  'A giant bear reading stories to a group of young animals, cozy campfire scene',
  'A flying whale passing by a city of floating islands, digital art',
  'A cat and a mouse working together to solve a mystery, detective style',
  'A magical waterfall that leads to a secret world filled with glowing creatures',
  'A family of robots playing board games in a cozy futuristic home',
  'A young inventor designing a flying skateboard, futuristic tech',
  'A mermaid and a pirate discovering a treasure chest on the ocean floor',
  'A glowing comet passing through the night sky, leaving a trail of sparkles',
  'A dragon creating colorful fireworks in the sky, magical celebration',
  'A robot dragon guarding a treasure chest in an ancient ruin, digital art',
  'A futuristic city built entirely out of crystals, glowing under the stars',
  'A magical forest where trees have faces and talk to travelers',
  'A robotic fish exploring the deep sea, surrounded by glowing coral',
  'A child creating a giant ice sculpture of a dragon in the snow',
  'A raccoon dressed as a knight, guarding a secret treasure chest',
  'A fairy flying above a city at night, casting a glowing trail behind',
  'A dinosaur walking through a peaceful park, interacting with children',
  'A spaceship shaped like a giant jellybean, traveling through the stars',
  'A panda painting a masterpiece in a sunny art studio',
  'A group of robots having a picnic in a park, chatting about technology',
  'A super-fast rabbit racing through a futuristic tunnel, digital art',
  'A time traveler visiting a Victorian-era city with advanced gadgets',
  'A young girl creating her own robot from scrap materials, futuristic scene',
  'A friendly alien exploring Earth’s gardens, taking notes on plants',
  'A giant turtle carrying an entire island on its back, fantasy art',
  'A penguin detective solving mysteries in the Arctic, cartoon style',
  'A spaceship landing on a peaceful moon, surrounded by floating crystals',
  'A cat flying a kite in a clear blue sky, enjoying a sunny day',
  'A giant dragon made of fire flying over a peaceful village',
  'A group of magical creatures living together in a floating island',
  'A robot learning to paint, creating a colorful masterpiece',
  'A child and a bear on a camping trip in the woods, digital art',
  'A young inventor creating a flying bicycle, futuristic concept',
  'A giant moon glowing over a peaceful ocean, magical scene',
  'A school of fish forming a giant heart shape underwater',
  'A group of friendly monsters teaching kids how to make art',
  'A futuristic city with buildings made of light, glowing at night',
  'A cat exploring an abandoned castle, discovering hidden treasures',
  'A wizard creating a portal to another dimension, surrounded by magic',
  'A superhero dolphin saving the ocean from pollution, digital art',
  'A group of children flying colorful kites on a warm spring day',
  'A friendly dragon sharing stories with kids in a magical forest',
  'A futuristic space station orbiting a distant planet, bustling with activity',
  'A cat in a hot air balloon, floating over a peaceful countryside',
  'A young girl with a glowing umbrella, walking through a magical rainstorm',
  'A giant fish swimming through the sky above a city at sunset',
  'A glowing rainbow made of stars arcing across the night sky',
  'A child and a puppy on a treasure hunt through a tropical jungle',
  'A cat exploring a cave filled with glowing crystals, magical atmosphere',
  'A group of animals planning a surprise birthday party for a friend',
  'A dragon and a phoenix flying through the clouds, surrounded by sparks',
  'A robot bird perched on a tree branch, observing the world below',
  'A magical treehouse in a giant oak tree, surrounded by floating lights',
  'A group of friends creating a giant sandcastle on a beach',
  'A mermaid singing a lullaby to the ocean, digital art',
  'A friendly giant walking through a city, helping people along the way',
  'A young wizard learning new spells in an enchanted library',
  'A futuristic farm where robots take care of the crops, digital art',
  'A castle made of candy and chocolate, surrounded by candy trees',
  'A magical butterfly flying through a glowing forest at night',
  'A group of animals hosting a talent show in a cozy theater',
  'A superhero dog flying through the clouds, ready for action',
  'A magical kingdom built on clouds, where everything is made of light',
  'A robot exploring an ancient ruin, discovering hidden artifacts',
  'A dragon flying above a city made entirely of mirrors',
  'A young child finding a magical book that can bring stories to life',
  'A group of children building a robot out of scrap materials, working together',
  'A space explorer discovering a new planet with friendly alien lifeforms',
  'A cat playing the violin in a cozy, dimly lit room, playing a beautiful melody',
  'A futuristic train traveling through a tunnel of light, zooming at high speed',
  'A talking tree giving advice to travelers in a mystical forest',
  'A superhero bear stopping a runaway train, saving the day',
  'A futuristic water park with flying slides and holographic dolphins',
  'A robot puppy learning to fetch, playing with a child in the yard',
  'A giant flower opening up to reveal a hidden treasure inside',
  'A child and a rabbit exploring an enchanted forest filled with glowing mushrooms',
  'A spaceship landing on a peaceful moon, surrounded by floating crystals',
  'A rainbow made of candy stretching across a bright blue sky',
  'A giant cloud shaped like an elephant, floating through a clear sky',
  'A group of kids solving a mystery in a spooky, abandoned mansion',
  'A forest of giant trees with glowing fireflies lighting the way',
  'A magical potion brewing in a cauldron, sending colorful smoke into the air',
  'A futuristic park with robots playing chess with kids, digital art',
  'A cat and a dog discovering a hidden tunnel under a tree, exploring together',
  'A giant octopus playing hide-and-seek with children, underwater scene',
  'A magical library where the books float around, glowing with light',
  'A young girl and her pet robot flying a kite together on a hilltop',
  'A dragon and a unicorn racing through the clouds, fast-paced scene',
  'A group of children discovering a magical pond where they can talk to animals',
  'A wizard casting spells to make the flowers bloom in a magical garden',
  'A futuristic city with holographic billboards and flying vehicles',
  'A family of animals on a road trip through a forest, having fun together',
  'A robot with a backpack going on an adventure in a bustling city',
  'A magical creature living in a hollow tree, watching over a secret garden',
  'A superhero owl flying through the night sky, ready to protect the city',
  'A friendly ghost giving kids a tour of an old haunted mansion',
  'A magical cloud castle floating above a busy city, glowing in the sun',
  'A group of animals preparing for a grand feast, setting up tables in the forest',
  'A young girl painting a mural on a giant wall, bringing it to life',
  'A rocket ship shaped like a giant ice cream cone, launching into space',
  'A dinosaur and a dragon becoming friends on an adventure, running through a magical land',
  'A cat exploring an ancient temple filled with golden treasures and traps',
  'A robot dog learning how to dance, impressing a group of children',
  'A young wizard learning to fly on a broomstick, zooming through the clouds',
  'A spaceship shaped like a giant flower, taking children on an intergalactic tour',
  'A mermaid swimming with dolphins in the deep blue ocean, magical scene',
  'A group of animals working together to build a treehouse, cartoon style',
  'A futuristic robot serving ice cream at a glowing stand in the park',
  'A magical forest where the trees whisper ancient secrets to those who listen',
  'A giant bear reading stories to a group of young animals, cozy campfire scene',
  'A flying whale passing by a city of floating islands, digital art',
  'A cat and a mouse working together to solve a mystery, detective style',
  'A magical waterfall that leads to a secret world filled with glowing creatures',
  'A family of robots playing board games in a cozy futuristic home',
  'A young inventor designing a flying skateboard, futuristic tech',
  'A mermaid and a pirate discovering a treasure chest on the ocean floor',
  'A glowing comet passing through the night sky, leaving a trail of sparkles',
  'A dragon creating colorful fireworks in the sky, magical celebration',
  'A robot dragon guarding a treasure chest in an ancient ruin, digital art',
  'A child creating a sculpture out of balloons in a park, whimsical art',
  'A robot learning to play the piano in a cozy living room',
  'A giant sloth taking a nap on top of a skyscraper, digital art',
  'A group of animals having a tea party in the middle of a meadow',
  'A superhero kitten saving the day with a cape, flying above the city',
  'A flying carpet carrying a family of adventurers through a stormy sky',
  'A mysterious cave with glowing crystals that light up the path ahead',
  'A child in a robot suit visiting an amusement park, digital art',
  'A magical garden where flowers bloom with every step you take',
  'A rocket made of candy, launching into space with a trail of sweets',
  'A young wizard casting a spell to bring a painting to life',
  'A group of animal friends taking a road trip in a colorful van',
  'A giant spider building a web around an old mansion, spooky atmosphere',
  'A futuristic city with holographic animals walking down the streets',
  'A magical broomstick sweeping leaves in a whimsical forest',
  'A robot dog helping a child clean their room, fun and interactive',
  'A flying dragon delivering letters to children in a magical village',
  'A giant mushroom growing in the middle of a busy city park',
  'A family of robots enjoying a holiday at the beach, digital art',
  'A cat wearing a detective hat solving a mystery in a bustling town',
  'A robot helping a baker create the perfect cake in a futuristic kitchen',
  'A child exploring an enchanted library with flying books and glowing scrolls',
  'A group of friendly bears hosting a summer barbecue in the forest',
  'A superhero rabbit saving the world with the power of kindness',
  'A glowing rainbow bridge connecting two magical islands in the sky',
  'A giant penguin exploring the Arctic with a group of penguin friends',
  'A treehouse made of candy, where animals come to play and relax',
  'A group of friendly monsters playing soccer in a park',
  'A futuristic zoo with holographic animals and robot caretakers',
  'A magical owl guiding a child through a forest at night',
  'A mermaid playing a harp, singing a song to the ocean waves',
  'A dinosaur and a child sharing a picnic in a prehistoric forest',
  'A group of animals holding a talent show in a forest clearing',
  'A space explorer discovering a new galaxy with glowing nebulae',
  'A friendly robot planting flowers in a community garden',
  'A child and their robot building a giant sandcastle at the beach',
  'A superhero dog leading a team of animal heroes on a rescue mission',
  'A magical fish guiding a child through an underwater kingdom',
  'A cat and a rabbit working together to build a treehouse',
  'A futuristic amusement park with rides that defy gravity',
  'A group of aliens teaching a child how to dance in zero gravity',
  'A snowman building itself with magical snowflakes in a winter wonderland',
  'A glowing jellyfish floating above a peaceful ocean at twilight',
  'A futuristic farm where crops are grown with light and sound',
  'A young inventor building a robot that can play chess, digital art',
  'A giant elephant flying through the clouds with a hot air balloon',
  'A robot exploring a colorful forest, interacting with the wildlife',
  'A group of animals taking a vacation to a tropical island',
  'A magical library where the books tell their own stories out loud',
  'A child and their pet exploring a hidden cave filled with treasure',
  'A futuristic vehicle shaped like a dragon, zooming through the sky',
  'A glowing butterfly leading a child through a mysterious garden',
  'A robot chef preparing the perfect dinner in a high-tech kitchen',
  'A young wizard casting spells to summon friendly creatures from books',
  'A playful dolphin jumping over a wave, with a rainbow trailing behind',
  'A magical tree that grows candy fruit, surrounded by smiling animals',
  'A dinosaur riding a bicycle through a prehistoric jungle',
  'A cat exploring a haunted house, discovering friendly ghosts',
  'A futuristic theme park with holographic attractions and rides',
  'A giant rainbow-colored fish swimming through the clouds',
  'A group of birds flying in formation, creating shapes in the sky',
  'A glowing star leading a child to a hidden treasure in a forest',
  'A magical potion brewing in a cauldron, filling the air with sparkles',
  'A cat wearing a wizard hat casting spells to make flowers bloom',
  'A family of rabbits going on an adventure through a magical field',
  'A superhero frog using a giant lily pad to save the day',
  'A group of fairies playing with fireflies in a glowing forest',
  'A child and a robot exploring a floating city made of light',
  'A dragon protecting a treasure chest filled with golden apples',
  'A talking parrot giving advice to a group of children',
  'A superhero cat swinging through a futuristic city, saving the day',
  'A magical garden where flowers change colors with each season',
  'A child and a giant robot painting a mural on a city wall',
  'A giant teddy bear hosting a birthday party for all the animals',
  'A group of animals riding roller coasters at an enchanted theme park',
  'A robot building a snowman in the middle of a winter city',
  'A young child with a glowing umbrella walking through a storm',
  'A group of animals playing musical instruments in a forest band',
  'A futuristic train passing through a tunnel made of light',
  'A magical butterfly leading a child to a hidden waterfall',
  'A family of friendly dinosaurs exploring a hidden jungle village',
  'A cat and a dog sharing a giant slice of pizza on a picnic blanket',
  'A spaceship shaped like a rocket ship made of candy, traveling to space',
  'A young wizard casting a spell to turn a pumpkin into a carriage',
  'A magical river flowing through a forest, glowing in the moonlight',
  'A group of children and robots building a castle out of blocks',
  'A group of talking animals helping to clean up a park after a storm',
  'A magical moon that grants wishes to those who catch a falling star',
  'A fairy guiding children through a secret door in a giant tree',
  'A superhero dog saving a family from a runaway hot air balloon',
  'A glowing fish guiding a group of children on an underwater adventure',
  'A young girl and her pet dragon discovering a hidden treasure in a cave',
  'A futuristic garden with plants that change colors with the seasons',
  'A robot helping a young girl organize her library, stacking books',
  'A magical snowstorm that creates glowing ice sculptures in the park',
  'A group of children flying their own rocket ships in a field',
  'A cat exploring a giant treehouse hidden deep in a mystical forest',
  'A glowing rainbow in the sky, leading to a magical castle',
  'A robot helping a chef bake cookies in a futuristic kitchen',
  'A young child walking through a forest where every tree is unique',
  'A superhero turtle using a giant shell to shield the city from danger',
  'A dragon helping a group of children on a quest to find a lost city',
  'A magical frog singing songs to the moon, surrounded by fireflies',
  'A group of friendly robots helping with chores in a futuristic home',
  'A friendly alien teaching children how to play space games',
  'A young girl and her robot exploring a hidden underwater city',
  'A magical butterfly leading a child through a forest filled with singing trees',
  'A superhero lion saving the jungle from a natural disaster',
  'A group of animals creating a giant snowman in the middle of a park',
  'A child and their robot exploring a glowing cave filled with ancient crystals',
  'A futuristic amusement park with rides that defy gravity and time',
  'A magical penguin sliding down an icy slide, laughing all the way',
  'A group of animals working together to build a treehouse',
  'A dragon soaring through the sky, spreading colorful sparks behind',
  'A young wizard learning new spells in a school for magic',
  'A space explorer discovering a hidden planet full of friendly aliens',
  'A child and their pet robot creating a glowing sculpture together',
  'A group of magical creatures sharing stories around a campfire',
  'A futuristic city filled with flying cars and towering skyscrapers',
  'A giant whale swimming through a glowing sea of stars',
  'A friendly ghost helping a group of children find their way home',
  'A robot bunny hopping through a springtime meadow, spreading joy',
  'A space shuttle flying through a galaxy filled with bright, colorful planets',
  'A superhero unicorn saving a city with a rainbow forcefield',
  'A magical forest where the trees whisper ancient secrets',
  'A giant whale flying through the sky, surrounded by fluffy clouds',
  'A futuristic city with robots serving ice cream on the streets',
  'A space explorer discovering an ancient alien civilization',
  'A giant panda building a sandcastle at the beach',
  'A group of kids flying through the clouds on magical carpets',
  'A treasure map hidden in a book, leading to a secret island',
  'A group of colorful birds singing in harmony in a forest clearing',
  'A child and their robot dog exploring the ruins of a forgotten city',
  'A robot chef making the perfect pancake for breakfast',
  'A glowing firefly lighting the way for a child in the forest',
  'A magical ship sailing across a sky filled with glowing stars',
  'A dinosaur wearing sunglasses riding a skateboard through the park',
  'A friendly alien offering a child a ride in their flying saucer',
  'A group of animals playing a soccer match on a giant mushroom',
  'A glowing jellyfish leading a group of kids on an underwater journey',
  'A giant octopus playing chess with a child in a secret cave',
  'A group of fairies painting the sky with colorful brushstrokes',
  'A dragon flying over a futuristic city with sparkling lights',
  'A young wizard casting a spell to bring books to life',
  'A glowing moon casting a magical glow over a snowy forest',
  'A futuristic zoo with robots taking care of exotic animals',
  'A magical tea party held by talking animals in a cozy cottage',
  'A young inventor creating a flying machine in their garage',
  'A futuristic robot cleaning the house while humming a tune',
  'A group of friendly ghosts hosting a party in an abandoned house',
  'A time-traveling robot visiting the ancient pyramids of Egypt',
  'A magical rainbow arching over a city at sunset',
  'A giant flower blooming in the middle of a busy city street',
  'A group of kids having a picnic with a giant, friendly elephant',
  'A superhero fox saving the forest from a storm with its superpowers',
  'A space explorer meeting an alien that looks like a giant flower',
  'A futuristic vehicle gliding smoothly over a glowing lake',
  'A magical ice cream truck serving treats to fairy tale creatures',
  'A giant robot playing with children in a park on a sunny day',
  'A space shuttle made of candy flying through a cotton candy sky',
  'A superhero squirrel saving the day by collecting falling acorns',
  'A magical playground where swings soar to the moon',
  'A group of animals building a treehouse high in the sky',
  'A young girl exploring a magical cavern filled with glowing crystals',
  'A futuristic amusement park where the rides are powered by starlight',
  'A magical dragon giving a child a ride on its back over a sparkling lake',
  'A group of robots having a friendly race through a futuristic city',
  'A fairy flying through a garden full of glowing flowers',
  'A group of animals building a castle out of colorful blocks',
  'A space robot exploring a distant planet with two moons',
  'A magical tree that grows fruit with glowing, rainbow-colored leaves',
  'A young adventurer discovering a hidden city in a jungle',
  'A group of kids exploring a magical cave with glowing crystals',
  'A superhero cat using its laser vision to stop a villain',
  'A giant panda riding a skateboard down a giant hill',
  'A magical fountain that grants wishes to anyone who touches the water',
  'A group of animals riding a giant roller coaster through the clouds',
  'A friendly robot taking care of a garden full of vibrant flowers',
  'A futuristic spaceship shaped like a giant butterfly flying through space',
  'A group of children playing hide-and-seek with friendly dinosaurs',
  'A friendly monster helping a group of kids find their lost toys',
  'A glowing butterfly leading children through a forest of sparkling trees',
  'A magical butterfly that transforms into a rainbow when touched',
  'A group of animals having a cooking competition in a magical kitchen',
  'A young wizard flying through the clouds on a broomstick made of stars',
  'A giant jellyfish glowing under the ocean, surrounded by sea creatures',
  'A robot guiding a group of children through a futuristic cityscape',
  'A superhero frog stopping a villain with its powerful jump',
  'A group of fairies using magic to turn pumpkins into carriages',
  'A magical snowman building itself in the middle of a forest',
  'A spaceship shaped like a giant cat zooming through space',
  'A glowing unicorn leading a group of kids through a magical forest',
  'A group of animals playing hide-and-seek in a giant sunflower field',
  'A friendly alien helping a group of kids with their homework',
  'A giant cloud shaped like a dragon soaring through the sky',
  'A futuristic theme park where robots control all the rides',
  'A magical forest where every tree has a different fruit on it',
  'A superhero turtle using its shell to shield the city from danger',
  'A group of kids finding a treasure chest hidden in the sand',
  'A robot dog helping a child with their school project',
  'A magical waterfall flowing with rainbow-colored water',
  'A glowing spaceship floating above a futuristic city at night',
  'A superhero rabbit using its super-speed to save the day',
  'A group of magical creatures decorating a giant Christmas tree',
  'A young girl discovering a hidden world inside her closet',
  'A friendly robot teaching kids how to build their own robots',
  'A futuristic jungle with glowing plants and animals made of light',
  'A magical forest where animals communicate by singing',
  'A group of kids riding a roller coaster through a rainbow-colored sky',
  'A glowing jellyfish floating above a calm, moonlit ocean',
  'A giant octopus playing musical instruments with its many arms',
  'A friendly robot helping kids clean up the park after a storm',
  'A futuristic library where the books come to life and tell stories',
  'A magical pond that shows a reflection of a magical kingdom',
  'A group of kids flying to the moon on a rocket ship made of candy',
  'A young wizard casting spells to make the clouds form into animals',
  'A group of animals having a parade through the streets of a magical city',
  'A glowing unicorn leading a group of children on a magical adventure',
  'A robot dog helping a child build a snowman in the winter',
  'A superhero panda saving a city from a giant, runaway balloon',
  'A group of fairies creating a rainbow in the sky using magic',
  'A giant octopus painting a masterpiece on the ocean floor',
  'A friendly alien showing a group of kids how to play an intergalactic game',
  'A magical kingdom hidden behind a waterfall, filled with dragons and fairies',
  'A group of kids flying through space on a rocket ship made of glitter',
  'A glowing star helping a child find their way home at night',
  'A futuristic robot helping a child with their homework using virtual reality',
  'A magical cave where the walls are covered in glowing gemstones',
  'A group of animals dancing under the moonlight in a forest clearing',
  'A space explorer finding a new planet filled with friendly creatures',
  'A superhero cat using its laser vision to stop a runaway train',
  'A glowing firefly lighting the way for a group of kids on a night adventure',
  'A magical creature with the body of a lion and the wings of an eagle',
  'A futuristic city on Mars with flying cars and giant holograms',
  'A group of kids having a snowball fight with friendly snowmen',
  'A time-traveling explorer visiting the ancient pyramids of Egypt',
  'A robot dog that can transform into a flying drone',
  'A mystical forest where animals wear tiny, colorful hats',
  'A magical carousel that moves through the sky instead of the ground',
  'A magical school where students learn how to talk to animals',
  'A superhero rabbit who can control the weather',
  'A group of fairies building tiny houses in the trunks of giant trees',
  'A futuristic city where people travel by walking on floating platforms',
  'A glowing dragon protecting a treasure chest made of gold',
  'A magical forest where the trees are made of candy',
  'A friendly octopus teaching kids how to solve math problems',
  'A group of kids using magic wands to make objects float',
  'A magical fish swimming through the air like a bird',
  'A time-traveling robot visiting the dinosaurs',
  'A superhero hamster who can create force fields',
  'A giant, friendly whale swimming through a cloud-filled sky',
  'A group of animals forming a rock band and playing music',
  'A futuristic city made entirely of glass and steel',
  'A group of kids riding on the back of a giant flying eagle',
  'A glowing unicorn leading a parade of magical creatures',
  'A robot cleaning up the beach and turning trash into beautiful sculptures',
  'A magical forest where every tree has its own unique song',
  'A young wizard discovering a spell that can make books float',
  'A superhero lion using its roar to stop an incoming storm',
  'A group of kids building a sandcastle with a giant sea turtle',
  'A glowing jellyfish floating inside a crystal cave',
  'A dragon with butterfly wings flying over a field of flowers',
  'A group of children discovering a hidden garden filled with talking flowers',
  'A magical library where the books can come to life and tell stories',
  'A robot inventor creating a flying machine made of scrap metal',
  'A glowing mushroom forest where the mushrooms change color when touched',
  'A group of fairies helping a young girl find her lost pet',
  'A superhero panda who can transform into different animals',
  'A futuristic zoo where all the animals are holograms',
  'A magical forest where animals wear tiny, glowing lanterns',
  'A superhero owl using its wisdom to solve a mysterious case',
  'A group of kids exploring a cave filled with glowing crystals',
  'A magical garden where plants sing lullabies at night',
  'A flying car zooming through a futuristic cityscape at night',
  'A group of animals having a dance party under the stars',
  'A robot puppy helping children with their homework',
  'A glowing phoenix rising from the ashes in a magical forest',
  'A magical toy store where the toys come to life after hours',
  'A superhero squirrel using its speed to stop a villain',
  'A futuristic city with towering skyscrapers and flying vehicles',
  'A glowing rainbow bridge connecting two magical lands',
  'A young girl riding on the back of a giant owl over a forest',
  'A magical carnival where the rides are powered by dreams',
  'A giant robot protecting a city from a powerful storm',
  'A group of fairies decorating the sky with sparkling stars',
  'A superhero zebra using its stripes to camouflage and sneak past villains',
  'A group of animals hosting a talent show in the jungle',
  'A magical treehouse floating in the sky, with a beautiful view of the stars',
  'A futuristic amusement park where robots are the ride attendants',
  'A glowing butterfly leading a group of children through a meadow at dusk',
  'A magical cloud kingdom where every cloud is made of cotton candy',
  'A time-traveling explorer discovering an ancient lost city',
  'A magical robot helping children with their science experiments',
  'A giant turtle floating on a cloud with a peaceful village on its back',
  'A friendly alien teaching kids how to make alien food in space',
  'A group of children flying on broomsticks through a magical forest',
  'A superhero kangaroo using its jumping powers to save the day',
  'A magical forest where the flowers grow in rainbow colors',
  'A robot making a sculpture out of snowflakes in the winter',
  'A group of kids exploring an underwater cave filled with glowing fish',
  'A friendly dragon giving a ride to a child through a cloud-filled sky',
  'A magical circus where all the performers are mythical creatures',
  'A group of animals riding roller coasters made of vines and trees',
  'A superhero mouse who can shrink down to the size of an ant',
  'A glowing jellyfish illuminating the ocean floor during a night dive',
  'A magical snowman that can create snowstorms with its magic hat',
  'A friendly giant helping a group of kids build the tallest tower',
  'A robot taking care of a garden full of talking flowers',
  'A time-traveling child visiting a medieval castle',
  'A magical tree that grows rainbow-colored fruits every season',
  'A superhero giraffe who can stretch its neck to incredible lengths',
  'A group of fairies building a tiny house out of acorns and leaves',
  'A glowing moon casting a soft light over a peaceful meadow',
  'A group of children riding unicorns through a field of sunflowers',
  'A magical dragon helping children solve riddles to find a hidden treasure',
  'A futuristic park where people use jetpacks to get around',
  'A group of kids traveling through a rainbow-colored tunnel to another world',
  'A superhero eagle who can fly faster than the speed of light',
  'A magical garden where the flowers bloom in patterns of stars',
  'A robot working at a candy factory, making the most delicious sweets',
  'A group of animals playing hide-and-seek in a magical orchard',
  'A young girl discovering a hidden door in her attic that leads to another world',
  'A glowing cloud that can turn into any shape the children imagine',
  'A superhero monkey using its strength to stop a runaway train',
  'A magical toy train that travels through time and space',
  'A giant panda riding a scooter through a futuristic city',
  'A group of kids discovering a secret underwater city',
  'A friendly alien guiding children through a futuristic space station',
  'A glowing firefly leading a child through a dark forest at night',
  'A serene sunset over a calm lake surrounded by mountains',
  'A vast desert with towering sand dunes stretching to the horizon',
  'A misty forest with tall trees and a soft, glowing light filtering through',
  'A magical garden filled with colorful flowers blooming under a rainbow',
  'A tropical beach with crystal clear water and palm trees swaying in the breeze',
  'A mountain range with snow-covered peaks under a starry night sky',
  'A rolling countryside with fields of golden wheat under a bright blue sky',
  'A peaceful village nestled between rolling hills and a sparkling river',
  'A dense jungle with towering trees, exotic plants, and hidden waterfalls',
  'A deep canyon with jagged rock formations and a river flowing through',
  'A calm lake with mist rising off the water in the early morning light',
  'A wide open plain with a vibrant orange sunset painting the sky',
  'A lush, green forest with sunlight filtering through the canopy',
  'A snowy mountain pass with a winding road and pine trees dusted in snow',
  'A dramatic cliffside overlooking the ocean, with waves crashing below',
  'A sprawling desert with scattered cacti and a hot sun blazing overhead',
  'A tranquil lake surrounded by autumn-colored trees with fallen leaves on the ground',
  'A wildflower meadow stretching across a valley, with a bright blue sky above',
  'A remote island with towering cliffs and waves crashing onto the shore',
  'A vibrant sunset over a city skyline with silhouettes of skyscrapers',
  'A deep forest clearing with a small pond reflecting the trees around it',
  'A tropical rainforest with dense foliage and exotic birds flying overhead',
  'A foggy morning in a small coastal town with boats anchored in the harbor',
  'A peaceful river winding through a valley, surrounded by towering mountains',
  'A rocky coastline with tide pools and crashing waves on a stormy day',
  'A majestic waterfall cascading down a cliff into a crystal-clear pool below',
  'A quiet beach at sunrise with soft pink and orange hues in the sky',
  'A vast savannah with acacia trees and a few grazing animals in the distance',
  'A peaceful valley with a winding stream and wildflowers dotting the grass',
  'A high-altitude mountain lake with clear blue water and jagged peaks surrounding it',
  'A dense fog rolling in over a quiet town by the sea, with lighthouse beams piercing through',
  'A glowing aurora borealis lighting up a snowy landscape under the stars',
  'A serene lake surrounded by autumn trees with bright red, orange, and yellow leaves',
  'A stunning view of the Grand Canyon at sunrise, with the rock formations glowing in the light',
  'A lush vineyard in the rolling hills of Tuscany with a bright blue sky overhead',
  'A barren volcanic landscape with black rock formations and sparse vegetation',
  'A coastal cliff with a lighthouse and dramatic waves crashing below',
  'A wild, untamed landscape with a meandering river and a large mountain in the distance',
  'A peaceful forest path leading through towering, ancient trees',
  'A tranquil pond in a Japanese garden with koi fish swimming beneath the surface',
  'A tropical island with clear blue water, white sand beaches, and dense palm trees',
  'A sprawling plain with a few scattered boulders and a colorful sunset in the distance',
  'A hidden valley with a small cottage nestled in the hills and a stream running through',
  'A high desert plateau with jagged rock formations and a vast sky overhead',
  'A colorful coral reef teeming with life just below the surface of crystal-clear water',
  'A misty morning in a coastal town with fishing boats bobbing in the harbor',
  'A rocky mountain pass with steep cliffs and alpine lakes dotting the landscape',
  'A vast grassland with rolling hills and a herd of wild horses galloping through',
  'A crystal-clear glacier-fed lake surrounded by tall pine trees',
  'A stunning panoramic view of the Scottish Highlands with misty mountains and green valleys',
  'A peaceful lake in a remote forest surrounded by tall, towering pines',
  'A rugged coastline with crashing waves and cliffs covered in wildflowers',
  'A quiet desert oasis with tall palm trees and a shimmering pond surrounded by sand',
  'A vibrant field of lavender stretching out to the horizon under a soft blue sky',
];

  

